package utils;

import java.lang.reflect.Modifier;
import java.util.Random;

public class RandomSupplier {
    private int methodCharNum = 97;
    private int varCharNum = 97;
    private int varRepeat = 0;
    private int methodRepeat = 0;
    private final static Random RANDOM = new Random();
    private final static String stringCandidates = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    static int MAX_STRING_LENGTH = 20;

    /**
     * @return a new unique variable-name
     */
    public String getVarName() {
        if (varCharNum == 123) {
            varRepeat++;
            varCharNum = 97;
        }
        char c = (char) varCharNum;
        varCharNum++;
        String character = String.valueOf(c);
        String name = character;
        for (int i = 0; i < varRepeat; i++) {
            name = name + character;
        }
        return name;
    }

    /**
     * @return @return a new unique Method-name, if only names generated by RANDOMSupplier are used
     */
    public String getMethodName() {
        if (methodCharNum == 123) {
            methodRepeat++;
            methodCharNum = 97;
        }
        char c = (char) methodCharNum;
        methodCharNum++;
        String character = String.valueOf(c);
        String name = "method" + character.toUpperCase();
        for (int i = 0; i < methodRepeat; i++) {
            name = name + character;
        }
        return name;
    }

    /**
     * @return a RANDOM FieldVarType
     */
    public static FieldVarType getFieldVarType() {
        int r = RANDOM.nextInt(FieldVarType.values().length - 1); //exclude void
        return FieldVarType.values()[r];
    }

    /**
     * @return an RANDOM array of ParameterTypes
     */
    public static FieldVarType[] getParameterTypes(int maxParameters) {
        int number = RANDOM.nextInt(maxParameters);
        FieldVarType[] types = new FieldVarType[number];
        for (int i = 0; i < number; i++) {
            types[i] = getFieldVarType();
        }
        return types;
    }

    /**
     * @return a RANDOM FieldType including type Void for ReturnType of a Method
     */
    public static FieldVarType getReturnType() {
        int r = RANDOM.nextInt(FieldVarType.values().length);
        return FieldVarType.values()[r];
    }

//    /**
//     * @param fieldVarType the fieldVarType of the value
//     * @return a RANDOM value of given FieldVarType
//     */
//    public static Object getRANDOMValue(FieldVarType fieldVarType) {
//        if (fieldVarType.getClazzType().getName().startsWith("java.lang")) {
//            //for Objects 25% chance to be initialized with null
//            if (RANDOM.nextInt(4) == 0) return null;
//        }
//        switch (fieldVarType) {
//            case Byte:
//                return (byte) RANDOM.nextInt();
//            case Short:
//                return (short) RANDOM.nextInt();
//            case Int:
//                return RANDOM.nextInt();
//            case Long:
//                return RANDOM.nextLong();
//            case Float:
//                return RANDOM.nextFloat();
//            case Double:
//                return RANDOM.nextDouble();
//            case Boolean:
//                return RANDOM.nextBoolean();
//            case Char:
//                return stringCandidates.charAt(RANDOM.nextInt(stringCandidates.length()));
//            case String:
//                return getString();
//            default:
//                return null;
//        }
//    }

    public static String getRandomValueAsString(FieldVarType fieldVarType) {
        if (fieldVarType.getClazzType().getName().startsWith("java.lang")) {
            //for Objects 25% chance to be initialized with null
            if (RANDOM.nextInt(4) == 0) return "null";
        }
        switch (fieldVarType) {
            case Byte:
                return "(byte)" + (byte) RANDOM.nextInt(Byte.MAX_VALUE + 1);
            case Short:
                return "(short)" + (short) RANDOM.nextInt(Short.MAX_VALUE + 1);
            case Int:
                return "" + RANDOM.nextInt();
            case Long:
                return RANDOM.nextLong() + "L";
            case Float:
                return RANDOM.nextFloat() + "f";
            case Double:
                return RANDOM.nextDouble() + "d";
            case Boolean:
                return "" + RANDOM.nextBoolean();
            case Char:
                return "\'" + stringCandidates.charAt(RANDOM.nextInt(stringCandidates.length())) + "\'";
            case String:
                return "\"" + getString() + "\"";
            default:
                return null;
        }
    }

    /**
     * @return a randomly generated String
     */
    public static String getString() {
        int length = RANDOM.nextInt(MAX_STRING_LENGTH + 1);
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < length; i++) {
            sb.append(stringCandidates.charAt(RANDOM.nextInt(stringCandidates.length())));
        }
        return sb.toString();
    }

    /**
     * @return random modifiers
     */
    public int getModifiers() {
        int numberOfModifiers = RANDOM.nextInt(4);
        int[] modifiers = new int[numberOfModifiers];
        int r = RANDOM.nextInt(5);
        int[] exclude_access = {2, 3, 4};
        for (int i = 1; i < numberOfModifiers; i++) {
            switch (r) {
                case 0:
                    modifiers[i] = Modifier.STATIC;
                    r = nextIntWithExcludes(5, 0);
                    break;
                case 1:
                    modifiers[i] = Modifier.FINAL;
                    r = nextIntWithExcludes(5, 1);
                    break;
                case 2:
                    modifiers[i] = Modifier.PUBLIC;
                    r = nextIntWithExcludes(5, exclude_access);
                    break;
                case 3:
                    modifiers[i] = Modifier.PRIVATE;
                    r = nextIntWithExcludes(5, exclude_access);
                    break;
                case 4:
                    modifiers[i] = Modifier.PROTECTED;
                    r = nextIntWithExcludes(5, exclude_access);
                    break;
            }
        }
        return mergeModifiers(modifiers);
    }

    /**
     * helper function for excluding added modifiers
     *
     * @param range
     * @param excludes
     * @return
     */
    private static int nextIntWithExcludes(int range, int... excludes) {
        int r = +RANDOM.nextInt(range);
        for (int i = 0; i < excludes.length; i++) {
            if (excludes[i] > r) {
                return r;
            }
            r++;
        }
        return r;
    }

    /**
     * megeres the given array of modifiers into one Integer-variable
     *
     * @param modifiers the modifiers to merge
     * @return the merged modifiers
     */
    private static int mergeModifiers(int[] modifiers) {
        if (modifiers.length == 0) return 0;

        int merged_modifiers = modifiers[0];
        for (int i = 1; i < modifiers.length; i++) {
            merged_modifiers |= modifiers[i];
        }
        return merged_modifiers;
    }

    /**
     * @param i the unique index of this parameter-variable-name
     * @return a unique parameter-variable-name, that is directly usable javassist's insertBefore/insertAfter-methods
     */
    public String getParVarName(int i) {
        return "$" + i;
    }

}
